{{- if or .Values.postgresExporter.enabled .Values.sqlExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcstask-monitoring.fullname" . }}-exporters
  labels:
    {{- include "fcstask-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATA_SOURCE_NAME: {{ include "fcstask-monitoring.database.dataSourceName" . | quote }}
{{- end }}
