{{- if .Values.postgresExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fcstask-monitoring.postgresExporter.fullname" . }}
  labels:
    {{- include "fcstask-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fcstask-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres-exporter
  template:
    metadata:
      labels:
        {{- include "fcstask-monitoring.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: "{{ .Values.postgresExporter.image.repository }}:{{ .Values.postgresExporter.image.tag }}"
          imagePullPolicy: {{ .Values.postgresExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9187
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "fcstask-monitoring.fullname" . }}-exporters
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
