apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fcstask-monitoring.prometheus.fullname" . }}
  labels:
    {{- include "fcstask-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fcstask-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "fcstask-monitoring.labels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          command:
            - /bin/sh
            - /etc/prometheus/entrypoint.sh
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "fcstask-monitoring.prometheus.fullname" . }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
            - name: data
              mountPath: /prometheus
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "fcstask-monitoring.prometheus.fullname" . }}
        - name: data
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
