apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcstask-monitoring.prometheus.fullname" . }}
  labels:
    {{- include "fcstask-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
type: Opaque
stringData:
  GRAFANA_CLOUD_REMOTE_WRITE_URL: {{ .Values.grafanaCloud.remoteWriteUrl | quote }}
  GRAFANA_CLOUD_REMOTE_WRITE_USERNAME: {{ .Values.grafanaCloud.remoteWriteUsername | quote }}
  GRAFANA_CLOUD_REMOTE_WRITE_PASSWORD: {{ .Values.grafanaCloud.remoteWritePassword | quote }}
